//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BebooGarden.Content {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BebooText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BebooText() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BebooGarden.Content.BebooText", typeof(BebooText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beboo Garden.
        /// </summary>
        public static string beboogarden {
            get {
                return ResourceManager.GetString("beboogarden", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pink.
        /// </summary>
        public static string pink {
            get {
                return ResourceManager.GetString("pink", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Red.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Orange.
        /// </summary>
        public static string orange {
            get {
                return ResourceManager.GetString("orange", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yellow.
        /// </summary>
        public static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Green.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blue.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Indigo.
        /// </summary>
        public static string indigo {
            get {
                return ResourceManager.GetString("indigo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Violet.
        /// </summary>
        public static string violet {
            get {
                return ResourceManager.GetString("violet", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A fat chocolate cake.
        /// </summary>
        public static string chocolatekake {
            get {
                return ResourceManager.GetString("chocolatekake", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A delicious icecream.
        /// </summary>
        public static string icecream {
            get {
                return ResourceManager.GetString("icecream", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A light and fresh fruit salad.
        /// </summary>
        public static string fruitsalad {
            get {
                return ResourceManager.GetString("fruitsalad", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Just a coffee, thanks..
        /// </summary>
        public static string coffee {
            get {
                return ResourceManager.GetString("coffee", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trees full of fruits.
        /// </summary>
        public static string trees_full {
            get {
                return ResourceManager.GetString("trees.full", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trees without any fruit.
        /// </summary>
        public static string trees_empty {
            get {
                return ResourceManager.GetString("trees.empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trees with some fruits.
        /// </summary>
        public static string trees_soonempty {
            get {
                return ResourceManager.GetString("trees.soonempty", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Trees with some fruits.
        /// </summary>
        public static string trees_soonfull {
            get {
                return ResourceManager.GetString("trees.soonfull", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have {0} tickets.
        /// </summary>
        public static string tickets {
            get {
                return ResourceManager.GetString("tickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à lagoon.
        /// </summary>
        public static string water {
            get {
                return ResourceManager.GetString("water", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apple.
        /// </summary>
        public static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Super Apple.
        /// </summary>
        public static string Energetic {
            get {
                return ResourceManager.GetString("Energetic", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} went asleep.
        /// </summary>
        public static string beboo_gosleep {
            get {
                return ResourceManager.GetString("beboo.gosleep", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} wakes up.
        /// </summary>
        public static string beboo_wakeup {
            get {
                return ResourceManager.GetString("beboo.wakeup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} burst in tears. Do something!.
        /// </summary>
        public static string beboo_sadstart {
            get {
                return ResourceManager.GetString("beboo.sadstart", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is happy!.
        /// </summary>
        public static string beboo_happystart {
            get {
                return ResourceManager.GetString("beboo.happystart", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is sleeping.
        /// </summary>
        public static string beboo_sleep {
            get {
                return ResourceManager.GetString("beboo.sleep", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is very tired.
        /// </summary>
        public static string beboo_verytired {
            get {
                return ResourceManager.GetString("beboo.verytired", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is very sad.. Do something!.
        /// </summary>
        public static string beboo_verysad {
            get {
                return ResourceManager.GetString("beboo.verysad", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is a little bit sad.
        /// </summary>
        public static string beboo_littlesad {
            get {
                return ResourceManager.GetString("beboo.littlesad", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is a little bit tired.
        /// </summary>
        public static string beboo_littletired {
            get {
                return ResourceManager.GetString("beboo.littletired", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is fine.
        /// </summary>
        public static string beboo_good {
            get {
                return ResourceManager.GetString("beboo.good", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is doing very well.
        /// </summary>
        public static string beboo_verygood {
            get {
                return ResourceManager.GetString("beboo.verygood", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music box.
        /// </summary>
        public static string musicbox_name {
            get {
                return ResourceManager.GetString("musicbox.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à An old object that can play music when putting a roll in it.
        /// </summary>
        public static string musicbox_description {
            get {
                return ResourceManager.GetString("musicbox.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don't have any roll to put in it yet.
        /// </summary>
        public static string musicbox_noroll {
            get {
                return ResourceManager.GetString("musicbox.noroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rubber duck.
        /// </summary>
        public static string duck_name {
            get {
                return ResourceManager.GetString("duck.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à It's just a duck.
        /// </summary>
        public static string duck_description {
            get {
                return ResourceManager.GetString("duck.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bouncing Boots.
        /// </summary>
        public static string boots_name {
            get {
                return ResourceManager.GetString("boots.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A Beboo can use them to bounce further. Place it on the ground then try make a beboo to put them on.
        /// </summary>
        public static string boots_description {
            get {
                return ResourceManager.GetString("boots.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tickets pack.
        /// </summary>
        public static string ticketpack_name {
            get {
                return ResourceManager.GetString("ticketpack.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jack pot!.
        /// </summary>
        public static string ticketpack_description {
            get {
                return ResourceManager.GetString("ticketpack.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} beboo's egg.
        /// </summary>
        public static string egg_name {
            get {
                return ResourceManager.GetString("egg.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à For more and more beboos!.
        /// </summary>
        public static string egg_description {
            get {
                return ResourceManager.GetString("egg.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bubble.
        /// </summary>
        public static string bubble_name {
            get {
                return ResourceManager.GetString("bubble.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Blup.
        /// </summary>
        public static string bubble_description {
            get {
                return ResourceManager.GetString("bubble.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snow ball.
        /// </summary>
        public static string snowball_name {
            get {
                return ResourceManager.GetString("snowball.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music box's roll.
        /// </summary>
        public static string roll_name {
            get {
                return ResourceManager.GetString("roll.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must type something..
        /// </summary>
        public static string ui_empty {
            get {
                return ResourceManager.GetString("ui.empty", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your name.
        /// </summary>
        public static string ui_yourname {
            get {
                return ResourceManager.GetString("ui.yourname", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Beboo has just hatched! Now it's time to name it!.
        /// </summary>
        public static string ui_letsname {
            get {
                return ResourceManager.GetString("ui.letsname", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your Beboo's cute name.
        /// </summary>
        public static string ui_bebooname {
            get {
                return ResourceManager.GetString("ui.bebooname", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the Beboo Adoption Centre! Someone put your name down for our programme. They mentioned you'd been on your own rather a lot lately, and thought you might like the company. I hope that's alright. Let's start with something easy: what should I call you?.
        /// </summary>
        public static string ui_welcome {
            get {
                return ResourceManager.GetString("ui.welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right, {0}, here is your garden. It's yours now, from all of us here at the centre. It's a wide square of greenery, with a small lagoon over to the left and tall fruit trees to the right. I'd put headphones on, if you have them: you'll find your way around this place by ear. There's an egg waiting on your right, about to hatch. Once I stop talking, walk over to it with the arrow keys, and when you hear it right in front of you, press space to help your beboo out of its shell..
        /// </summary>
        public static string ui_welcome2 {
            get {
                return ResourceManager.GetString("ui.welcome2", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Great! Now, {0}, I have to ask you a few questions to find the Beboo who suits you best. Let's start simple..
        /// </summary>
        public static string ui_aboutyou {
            get {
                return ResourceManager.GetString("ui.aboutyou", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à What is your favorite color?.
        /// </summary>
        public static string ui_color {
            get {
                return ResourceManager.GetString("ui.color", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cool! Now, what do you love doing when you have some free time? It may be anything..
        /// </summary>
        public static string ui_freetime {
            get {
                return ResourceManager.GetString("ui.freetime", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à What do you love to do?.
        /// </summary>
        public static string ui_freetimequick {
            get {
                return ResourceManager.GetString("ui.freetimequick", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finally, what is your favorite dessert in this list?.
        /// </summary>
        public static string ui_dessert {
            get {
                return ResourceManager.GetString("ui.dessert", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Well, everything seems in order..
        /// </summary>
        public static string ui_allgood {
            get {
                return ResourceManager.GetString("ui.allgood", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à There we are. Before I leave you to it, the things that matter. Food: shake the trees on your right by holding enter and alternating up and down. Then stand next to {0} and press space to offer a fruit, the same way you helped with the egg. Press F at any time and I'll tell you how {0} is doing: how happy, how tired. P picks {0} up. While you're holding it, hold enter and alternate left and right to rock it. Gently, mind. Rock it steadily and it falls asleep in your arms; shake it about and it will cry, and it will remember. This garden isn't the only place. As you go on, paths open to other places, and you cross by pressing enter where you hear one. Your beboo won't follow you on its own, so whistle with space before you go, or call it by its number, and it will come along with you. It's worth taking it places. A beboo that only ever sees one field gets bored. Escape opens the menu. That's everything. Enjoy each other..
        /// </summary>
        public static string ui_quicktips {
            get {
                return ResourceManager.GetString("ui.quicktips", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nothing in the bag.
        /// </summary>
        public static string ui_emptyinventory {
            get {
                return ResourceManager.GetString("ui.emptyinventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose an item.
        /// </summary>
        public static string ui_chooseitem {
            get {
                return ResourceManager.GetString("ui.chooseitem", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} dropped.
        /// </summary>
        public static string ui_itemput {
            get {
                return ResourceManager.GetString("ui.itemput", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don't put this in water!.
        /// </summary>
        public static string ui_warningwater {
            get {
                return ResourceManager.GetString("ui.warningwater", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have taken the music box's roll {0}, from {1}.
        /// </summary>
        public static string ui_rolltake {
            get {
                return ResourceManager.GetString("ui.rolltake", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please choose a roll to insert.
        /// </summary>
        public static string ui_chooseroll {
            get {
                return ResourceManager.GetString("ui.chooseroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} stored in the bag.
        /// </summary>
        public static string ui_itemtake {
            get {
                return ResourceManager.GetString("ui.itemtake", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are {0} fruits in the basket.
        /// </summary>
        public static string ui_basket {
            get {
                return ResourceManager.GetString("ui.basket", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Back.
        /// </summary>
        public static string ui_back {
            get {
                return ResourceManager.GetString("ui.back", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : {1}, {2} tickets.
        /// </summary>
        public static string shop_item {
            get {
                return ResourceManager.GetString("shop.item", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Items ({0} remaining tickets).
        /// </summary>
        public static string shop_items {
            get {
                return ResourceManager.GetString("shop.items", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Items.
        /// </summary>
        public static string shop_itemstitle {
            get {
                return ResourceManager.GetString("shop.itemstitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music box roll's ({0} remaining tickets).
        /// </summary>
        public static string shop_rolls {
            get {
                return ResourceManager.GetString("shop.rolls", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} : {1}, {2} tickets.
        /// </summary>
        public static string shop_roll {
            get {
                return ResourceManager.GetString("shop.roll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music Box roll's.
        /// </summary>
        public static string shop_rollstitle {
            get {
                return ResourceManager.GetString("shop.rollstitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You already have this roll.
        /// </summary>
        public static string shop_alreadyroll {
            get {
                return ResourceManager.GetString("shop.alreadyroll", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You don't have enough tickets.
        /// </summary>
        public static string shop_notickets {
            get {
                return ResourceManager.GetString("shop.notickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the boutique! ({0} remaining tickets).
        /// </summary>
        public static string shop_title {
            get {
                return ResourceManager.GetString("shop.title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} bought.
        /// </summary>
        public static string shop_buy {
            get {
                return ResourceManager.GetString("shop.buy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} (×{1}).
        /// </summary>
        public static string inventory_item {
            get {
                return ResourceManager.GetString("inventory.item", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find an item.
        /// </summary>
        public static string tp {
            get {
                return ResourceManager.GetString("tp", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} {1}.
        /// </summary>
        public static string tp_item {
            get {
                return ResourceManager.GetString("tp.item", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You gain {0} ticket.
        /// </summary>
        public static string gainticket {
            get {
                return ResourceManager.GetString("gainticket", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You unlock the boutique! Go to the lower right corner of the garden to redeem your tickets!.
        /// </summary>
        public static string shopunlock {
            get {
                return ResourceManager.GetString("shopunlock", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boutique.
        /// </summary>
        public static string shop {
            get {
                return ResourceManager.GetString("shop", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is the third....
        /// </summary>
        public static string race_third {
            get {
                return ResourceManager.GetString("race.third", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is the second. ({1} seconds).
        /// </summary>
        public static string race_second {
            get {
                return ResourceManager.GetString("race.second", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is the first! ({1} seconds).
        /// </summary>
        public static string race_first {
            get {
                return ResourceManager.GetString("race.first", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Take part in a race ({0} remaining today).
        /// </summary>
        public static string race_gate {
            get {
                return ResourceManager.GetString("race.gate", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose your racer.
        /// </summary>
        public static string race_chooseracer {
            get {
                return ResourceManager.GetString("race.chooseracer", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a race.
        /// </summary>
        public static string race_chooserace {
            get {
                return ResourceManager.GetString("race.chooserace", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Racing is closed for today..
        /// </summary>
        public static string race_trytommorow {
            get {
                return ResourceManager.GetString("race.trytommorow", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Easy race.
        /// </summary>
        public static string race_simple {
            get {
                return ResourceManager.GetString("race.simple", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Snowy race.
        /// </summary>
        public static string race_snow {
            get {
                return ResourceManager.GetString("race.snow", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is now old enough to recognize its name! Try calling it!.
        /// </summary>
        public static string unlockvoice {
            get {
                return ResourceManager.GetString("unlockvoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Congratulations! You unlock the path to the snowy area. Go through it by calling your Beboo to the bottom left of the garden..
        /// </summary>
        public static string unlocksnowy {
            get {
                return ResourceManager.GetString("unlocksnowy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Congratulations! {0} can perfectly swim now..
        /// </summary>
        public static string unlockswimming {
            get {
                return ResourceManager.GetString("unlockswimming", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Path.
        /// </summary>
        public static string path {
            get {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no beboo here..
        /// </summary>
        public static string nobeboo {
            get {
                return ResourceManager.GetString("nobeboo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volcanic underwater chimney.
        /// </summary>
        public static string underwater {
            get {
                return ResourceManager.GetString("underwater", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a Beboo.
        /// </summary>
        public static string choosebeboo {
            get {
                return ResourceManager.GetString("choosebeboo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Main menu.
        /// </summary>
        public static string ui_mainmenu {
            get {
                return ResourceManager.GetString("ui.mainmenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help: Game's keybindings.
        /// </summary>
        public static string ui_commands {
            get {
                return ResourceManager.GetString("ui.commands", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Credits.
        /// </summary>
        public static string ui_credits {
            get {
                return ResourceManager.GetString("ui.credits", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Join the discord server.
        /// </summary>
        public static string ui_discord {
            get {
                return ResourceManager.GetString("ui.discord", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close the Game..
        /// </summary>
        public static string ui_quit {
            get {
                return ResourceManager.GetString("ui.quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bag.
        /// </summary>
        public static string bag {
            get {
                return ResourceManager.GetString("bag", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your bag is empty (escape to leave).
        /// </summary>
        public static string emptybag {
            get {
                return ResourceManager.GetString("emptybag", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are no items here. To place an item, go to your bag, select an item then press space where you want to place it..
        /// </summary>
        public static string ui_emptymap {
            get {
                return ResourceManager.GetString("ui.emptymap", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change language.
        /// </summary>
        public static string ui_language {
            get {
                return ResourceManager.GetString("ui.language", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language changed.
        /// </summary>
        public static string ui_languagechanged {
            get {
                return ResourceManager.GetString("ui.languagechanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You win!.
        /// </summary>
        public static string win {
            get {
                return ResourceManager.GetString("win", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You lose..
        /// </summary>
        public static string lose {
            get {
                return ResourceManager.GetString("lose", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Boom Box.
        /// </summary>
        public static string boombox {
            get {
                return ResourceManager.GetString("boombox", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Score: {0}.
        /// </summary>
        public static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to Boom Box!.
        /// </summary>
        public static string welcome {
            get {
                return ResourceManager.GetString("welcome", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Press the numbers on the keyboard to hear a sound. Find all the pairs to move to the next level..
        /// </summary>
        public static string goal {
            get {
                return ResourceManager.GetString("goal", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Treasure chest.
        /// </summary>
        public static string chest_name {
            get {
                return ResourceManager.GetString("chest.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A chest full of tickets. But be careful! A Beboo must be wit to get them..
        /// </summary>
        public static string chest_description {
            get {
                return ResourceManager.GetString("chest.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find a Beboo.
        /// </summary>
        public static string findbeboo {
            get {
                return ResourceManager.GetString("findbeboo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rubber ring.
        /// </summary>
        public static string rubberring_name {
            get {
                return ResourceManager.GetString("rubberring.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Floating beboo isn't water scared.
        /// </summary>
        public static string rubberring_description {
            get {
                return ResourceManager.GetString("rubberring.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fish.
        /// </summary>
        public static string fish_name {
            get {
                return ResourceManager.GetString("fish.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à It's just a fish.
        /// </summary>
        public static string fish_description {
            get {
                return ResourceManager.GetString("fish.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You take {0} in your arms.
        /// </summary>
        public static string beboo_pickup {
            get {
                return ResourceManager.GetString("beboo.pickup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You put {0} back down.
        /// </summary>
        public static string beboo_putdown {
            get {
                return ResourceManager.GetString("beboo.putdown", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} falls asleep in your arms.
        /// </summary>
        public static string beboo_sleepinarms {
            get {
                return ResourceManager.GetString("beboo.sleepinarms", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You shake {0} way too hard, and it bursts into tears!.
        /// </summary>
        public static string beboo_swaytoohard {
            get {
                return ResourceManager.GetString("beboo.swaytoohard", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your hands are already full.
        /// </summary>
        public static string beboo_handsfull {
            get {
                return ResourceManager.GetString("beboo.handsfull", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Competition center ({0} tries left today).
        /// </summary>
        public static string competition_gate {
            get {
                return ResourceManager.GetString("competition.gate", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a competition.
        /// </summary>
        public static string competition_choose {
            get {
                return ResourceManager.GetString("competition.choose", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Race.
        /// </summary>
        public static string competition_race {
            get {
                return ResourceManager.GetString("competition.race", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The competition center is closed for today. Come back tomorrow!.
        /// </summary>
        public static string competition_closed {
            get {
                return ResourceManager.GetString("competition.closed", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jumpidy Jump.
        /// </summary>
        public static string jump_name {
            get {
                return ResourceManager.GetString("jump.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jumpidy Jump! Whoever jumps the furthest wins..
        /// </summary>
        public static string jump_start {
            get {
                return ResourceManager.GetString("jump.start", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} jumped {1} metres.
        /// </summary>
        public static string jump_jumped {
            get {
                return ResourceManager.GetString("jump.jumped", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} jumped the furthest, {1} metres, and wins!.
        /// </summary>
        public static string jump_win {
            get {
                return ResourceManager.GetString("jump.win", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is exhausted.
        /// </summary>
        public static string beboo_exhausted {
            get {
                return ResourceManager.GetString("beboo.exhausted", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is tired.
        /// </summary>
        public static string beboo_tired {
            get {
                return ResourceManager.GetString("beboo.tired", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is doing okay.
        /// </summary>
        public static string beboo_okenergy {
            get {
                return ResourceManager.GetString("beboo.okenergy", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is full of energy.
        /// </summary>
        public static string beboo_energetic {
            get {
                return ResourceManager.GetString("beboo.energetic", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} ({1} tries left today).
        /// </summary>
        public static string competition_entry {
            get {
                return ResourceManager.GetString("competition.entry", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nest.
        /// </summary>
        public static string nest_name {
            get {
                return ResourceManager.GetString("nest.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A soft bed. A beboo sleeping in one wakes up better rested, and a sleepy beboo will go and find it..
        /// </summary>
        public static string nest_description {
            get {
                return ResourceManager.GetString("nest.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} snuggles up against {1}.
        /// </summary>
        public static string beboo_snuggle {
            get {
                return ResourceManager.GetString("beboo.snuggle", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} comes back and drops {1} at your feet!.
        /// </summary>
        public static string beboo_present {
            get {
                return ResourceManager.GetString("beboo.present", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} comes back with something shiny!.
        /// </summary>
        public static string beboo_presentticket {
            get {
                return ResourceManager.GetString("beboo.presentticket", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mods. Tick the ones you want, then choose play..
        /// </summary>
        public static string mods_title {
            get {
                return ResourceManager.GetString("mods.title", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        public static string mods_play {
            get {
                return ResourceManager.GetString("mods.play", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}, adds {1} creature(s).
        /// </summary>
        public static string mods_entrycreatures {
            get {
                return ResourceManager.GetString("mods.entrycreatures", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}, in use.
        /// </summary>
        public static string mods_inuse {
            get {
                return ResourceManager.GetString("mods.inuse", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} cannot be switched off: you already have {1}. Give them away or let them go first..
        /// </summary>
        public static string mods_cantdisable {
            get {
                return ResourceManager.GetString("mods.cantdisable", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can't put anything down here..
        /// </summary>
        public static string ui_cantputhere {
            get {
                return ResourceManager.GetString("ui.cantputhere", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} goes back in your bag..
        /// </summary>
        public static string ui_itembacktobag {
            get {
                return ResourceManager.GetString("ui.itembacktobag", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluff.
        /// </summary>
        public static string fluff {
            get {
                return ResourceManager.GetString("fluff", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fluffball.
        /// </summary>
        public static string fluffball_name {
            get {
                return ResourceManager.GetString("fluffball.name", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A small round thing made entirely of fluff. It hugs whatever it bumps into..
        /// </summary>
        public static string fluffball_description {
            get {
                return ResourceManager.GetString("fluffball.description", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball hugs you. It is extremely soft..
        /// </summary>
        public static string fluffball_hugyou {
            get {
                return ResourceManager.GetString("fluffball.hugyou", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball hugs {0}, who goes all cute about it..
        /// </summary>
        public static string fluffball_hugbeboo {
            get {
                return ResourceManager.GetString("fluffball.hugbeboo", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} is happy enough for a day out! A soft little place called the fluff has opened up, at the top right of the garden. There is nothing to do there at all. That is rather the point..
        /// </summary>
        public static string unlockfluff {
            get {
                return ResourceManager.GetString("unlockfluff", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        public static string ui_yes {
            get {
                return ResourceManager.GetString("ui.yes", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        public static string ui_no {
            get {
                return ResourceManager.GetString("ui.no", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pick up {0}?.
        /// </summary>
        public static string ui_confirmpickup {
            get {
                return ResourceManager.GetString("ui.confirmpickup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mods.
        /// </summary>
        public static string ui_mods {
            get {
                return ResourceManager.GetString("ui.mods", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Done.
        /// </summary>
        public static string mods_done {
            get {
                return ResourceManager.GetString("mods.done", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ask before picking things up.
        /// </summary>
        public static string mods_confirm_pickup {
            get {
                return ResourceManager.GetString("mods.confirm-pickup", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball snuggles into {0} and settles there. It has picked its beboo..
        /// </summary>
        public static string fluffball_attached {
            get {
                return ResourceManager.GetString("fluffball.attached", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball tags along after {0}..
        /// </summary>
        public static string fluffball_follows {
            get {
                return ResourceManager.GetString("fluffball.follows", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sound memory. {0} cases. Press 1 to {0} to hear one, and find the pairs. {1} mistakes allowed. Escape to give up..
        /// </summary>
        public static string memory_start {
            get {
                return ResourceManager.GetString("memory.start", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à You gave up..
        /// </summary>
        public static string memory_quit {
            get {
                return ResourceManager.GetString("memory.quit", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball will not follow {0} into the cold, and stays where it is..
        /// </summary>
        public static string fluffball_staysbehind {
            get {
                return ResourceManager.GetString("fluffball.staysbehind", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball has nobody left to hug, and goes quiet and sad..
        /// </summary>
        public static string fluffball_alone {
            get {
                return ResourceManager.GetString("fluffball.alone", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball has company again, and perks right up..
        /// </summary>
        public static string fluffball_cheered {
            get {
                return ResourceManager.GetString("fluffball.cheered", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The fluffball has waited long enough, and drifts away home to the fluff..
        /// </summary>
        public static string fluffball_goeshome {
            get {
                return ResourceManager.GetString("fluffball.goeshome", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume {0}%..
        /// </summary>
        public static string ui_volume {
            get {
                return ResourceManager.GetString("ui.volume", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music volume {0}%..
        /// </summary>
        public static string ui_musicvolume {
            get {
                return ResourceManager.GetString("ui.musicvolume", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music off..
        /// </summary>
        public static string ui_musicmuted {
            get {
                return ResourceManager.GetString("ui.musicmuted", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Music on..
        /// </summary>
        public static string ui_musicunmuted {
            get {
                return ResourceManager.GetString("ui.musicunmuted", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à A snowball would not last a minute in the fluff..
        /// </summary>
        public static string snowball_toowarm {
            get {
                return ResourceManager.GetString("snowball.toowarm", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your beboo is {0}!.
        /// </summary>
        public static string ui_hatchcolor {
            get {
                return ResourceManager.GetString("ui.hatchcolor", resourceCulture);
            }
        }

            /// <summary>
        ///   Touch-worded version of ui.welcome2, for platforms with no keyboard.
        /// </summary>
        public static string ui_welcome2_touch {
            get {
                return ResourceManager.GetString("ui.welcome2.touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Touch-worded version of ui.quicktips, for platforms with no keyboard.
        /// </summary>
        public static string ui_quicktips_touch {
            get {
                return ResourceManager.GetString("ui.quicktips.touch", resourceCulture);
            }
        }
        
}
}
